name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a job called "unit_tests"
  unit_tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3

      - uses: syphar/restore-virtualenv@v1.2
        id: venv
        with:
          requirement_files: Code/requirements.txt

      - uses: syphar/restore-pip-download-cache@v1
        if: steps.venv.outputs.cache-hit != 'true'

      - run: pip install -r Code/requirements.txt
        if: steps.venv.outputs.chache-hit != 'true'

      - name: unit_tests
        run: cd Code ; python -m pytest unit_test

  PEP8:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3

      - name: Flake8
        run: pip install flake8; flake8 Code/main.py

  Pylint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3

    - name: Pylint
      run: pip install pylint; pylint Code/main.py
